# Generated by Django 6.1.1 on 2026-09-15 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('visit_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daily_limit', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freeze_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abonement turi',
                'verbose_name_plural': 'Abonement turlari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('card_code', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('visits_used', models.PositiveSmallIntegerField(default=0)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('muzlatilgan', 'Muzlatilgan'), ('tugagan', 'Tugagan'), ('bekor', 'Bekor qilingan')], default='faol', max_length=20)),
                ('reminder_sent_at', models.DateField(blank=True, help_text='Oxirgi eslatma yuborilgan sana', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'Sotilgan abonement',
                'verbose_name_plural': 'Sotilgan abonementlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_freezes', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='memberships.membership')),
            ],
            options={
                'verbose_name': 'Muzlatish',
                'verbose_name_plural': 'Muzlatishlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('ruxsat', 'Ruxsat'), ('muddati_tugagan', 'Muddati tugagan'), ('muzlatilgan', 'Muzlatilgan'), ('limit_tugagan', 'Limit tugagan'), ('topilmadi', 'Topilmadi')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='memberships.membership')),
            ],
            options={
                'verbose_name': 'Kirish urinishi',
                'verbose_name_plural': 'Kirish urinishlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_visits', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='memberships.membership')),
            ],
            options={
                'verbose_name': 'Tashrif',
                'verbose_name_plural': 'Tashriflar',
                'ordering': ('-checked_in_at',),
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['client', 'status'], name='memberships_client__8a5008_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'faol')), fields=('client',), name='unique_active_membership_per_client'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['membership', 'checked_in_at'], name='memberships_members_ac75db_idx'),
        ),
    ]
